config/routes.rb
TheShelf::Application.routes.draw do
  scope module: :api do
    scope module: :v1, constraints: ApiConstraint.new(version: 1) do
      devise_for :users, skip: [:sessions]
      resource :session, only: [:create]
      resources :books do
        resource :loan, only: [:create, :destroy, :update]
      end
      resources :users, only: [:create, :show, :index]
    end
  end
end

app/models/book.rb
require_relative 'lendable'
require_relative 'reviewable'
require_relative 'rateable'

class Book < ActiveRecord::Base
  include Lendable
  include Reviewable
  include Rateable

  has_many :borrowers, through: :loans
  has_many :loans

  validates :isbn, uniqueness: true
  validates :title, :state, :authors, presence: true
  validates :state, inclusion: { in: LoanStates.all }

  mount_uploader :cover, CoverUploader

  def current_borrower
    current_loan.borrower
  end

  def current_loan
    loans.by_most_recent.first
  end

  def current_loan_by(borrower)
    loans.where(user_id: borrower.id).by_most_recent.first
  end

  def extendable?
    !available? && current_loan.extendable?
  end

  def self.search(query)
    if query
      where('title LIKE ? or authors LIKE ?', "%#{query}%", "%#{query}%")
    else
      all
    end
  end
end

app/controllers/api/v1/books_controller.rb
module API
  module V1
    class BooksController < ApplicationController
      authorize_resource

      def index
        books = Book.all

        render json: books
      end

      def show
        render json: Book.find(params[:id])
      end

      def destroy
        book = Book.find(params[:id])
        book.destroy
        render json: book
      end

      def update
        book = Book.find(params[:id])
        book.update(book_params)
        render json: book
      end

      def create
        book = Book.new(book_params)

        if book.save
          render json: book, status: :created, location: book_url(book)
        else
          head :bad_request
        end
      end

      private

      def book_params
        params.require(:book).permit(:authors, :owner, :pages, :published_on, :subtitle, :summary, :title, :url, :cover, :cover_cache, :isbn)
      end
    end
  end
end

app/views/books/new_review.slim
section.default-page.book-page
  h1.mega = t('reviews.new.title')

  .book-cover
    .book-image
      = image_tag @book.cover
  .book-info
    .milli = @book.title
    .nano = @book.subtitle
    p.small = @book.authors

  .new-section
    h2.milli = t('reviews.new.rating_title')
    = render 'my_rating', book: @book

  .new-section
    h2.milli = t('reviews.new.comment_title')
    = form_tag create_review_book_path, method: 'post', class: 'review-form'
      fieldset
        label.hide-visually :review_body
        .text = text_area :review, :body, placeholder: t('forms.reviews.comment')
      .form-actions
        = link_to t('reviews.new.skip_review'), book_path(@book), class: 'btn-negative'
        = submit_tag t('forms.reviews.submit'), class: 'btn-positive'